name: Cuán buenas fueron las predicciones estadísticas del Mundial
title: Cuán buenas fueron las predicciones estadísticas del Mundial
description: El fútbol es un deporte bastante difícil de predecir. ¿Es la probabilidad la herramienta adecuada para esto?
url: https://seppo0010.github.io/analisis-predicciones-mundial-2022/
author: seppo0011
twitter:
  username: seppo0011
site:
  image:
    path: /analisis-predicciones-mundial-2022/img.jpg
    width: 2048
    height: 1152
    alt: Copa del Mundo
